export const levelOne =[

    {name:"earth",
    type:"sun",
    active: true,
    focus: false,
    tracked: false,
    children: [


        {name: "zen",
        order:2,
        active: false,
        focus: true,
        tracked: false,
        flow:1,
        children:[


               { name: "valerie",
                type:"moon",
                parent:"yin",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                children: [],
                flow:1,
                angl:10,
                dist:140},

                { name: "lucy",
                type:"moon",
                parent:"yin",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                children: [     {name: "max",
                                parent:"yin",
                                active: false,
                                focus: false,
                                tracked: false,
                                children: [],
                                flow:1,
                                angl:100,
                                dist:80},
            
                                {name: "anna",
                                parent:"yin",
                                active: false,
                                focus: false,
                                tracked: false,
                                children: [],
                                flow:2,
                                angl:190,
                                dist:80},
                            
                                {name: "sam",
                                parent:"yin",
                                active: false,
                                focus: false,
                                tracked: false,
                                children: [],
                                flow:3,
                                angl:290,
                                dist:80}],

                flow:2,
                angl:130,
                dist:170},

                { name:"jay",
                parent:"yin",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                children: [],
                flow:3,
                angl:250,
                dist:130}


        ],
        parent:"earth",
        angl:50,
        dist:300},
            
        { name: "gaia",
        order:2,
        done:false,
        active: false,
        focus: false,
        tracked: false,
        flow:2,
        children:[

            {   name: "venus",
                parent:"zen",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                base:true,
                children: [],
                flow:1,
                angl:10,
                dist:150},

            {   name: "ash",
                parent:"zen",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                children: [],
                flow:2,
                angl:130,
                dist: 150},

                { name: "mo",
                parent:"zen",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                children: [],
                flow:3,
                angl:250,
                dist:140},

        ],
        parent:"earth",
        angl:170,
        dist:300
    },
    
        { name: "yin",
        order:2,
        done:false,
        active: false,
        focus: false,
        tracked: false,
        flow:3,
        children:[

            {   name: "goa",
                parent:"gaia",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                base:true,
                children:[],
                flow:1,
                angl:70,
                dist:150},

            {   name: "runa",
                parent:"gaia",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                children: [     {name: "max",
                                parent:"runa",
                                active: false,
                                focus: false,
                                tracked: false,
                                children: [],
                                flow:1,
                                angl:90,
                                dist:90},
                            
                                {name: "anna",
                                parent:"runa",
                                active: false,
                                focus: false,
                                tracked: false,
                                children: [],
                                flow:2,
                                angl:250,
                                dist:120},
                            
                                {name: "sam",
                                parent:"runa",
                                active: false,
                                focus: false,
                                tracked: false,
                                children: [],
                                flow:3,
                                angl:320,
                                dist:80}]
                
                ,
                flow:2,
                angl:190,
                dist:140},

            {   name: "leo",
                parent:"gaia",
                order:3,
                active: false,
                focus: false,
                tracked: false,
                children: [],
                flow:3,
                angl:310,
                dist:120},


        ],
        parent:"earth",
        angl:290,
        dist:300}]

}]
        
    





