export default {
  level: [
    {
      name: 'alderaan',
      id: '0',
      tracked: true,
      children: [
        {
          name: 'endor',
          id: '1',
          children: [],
          limit: true,
          parent: 'alderaan',
          angl: 50,
          dist: 200,
          ring: 0,
        },
        {
          name: 'jakku',
          id: '2',
          children: [
            {
              name: 'naboo',
              id: '2.1',
              children: [],
              parent: 'jakku',
              limit: true,
              angl: 120,
              dist: 110,
              ring: 0,
            },
          ],
          parent: 'alderaan',
          angl: 170,
          dist: 130,
        },
        {
          name: 'tatooine',
          id: '3',
          active: true,
          tracked: true,
          children: [],
          limit: true,
          parent: 'alderaan',
          angl: 290,
          dist: 130,
          ring: 0,
        },
      ],
    },
  ],
  max: 6,
  initialId: '3',
  initialPosition: 'tatooine',
  initialFocus: false,
  initialParent: 'alderaan',
  charge: 'endor',
  goal: 'naboo',
  thisLevel: 2,
  nextLevel: 'levelthree',
  atronautName: 'luke',
  galaxyName: "skywalker's universe",
};
