export default {
  level: [
    {
      name: 'alderaan',
      id: '0',
      scope: 0,
      active: false,
      focus: false,
      tracked: true,
      limit: false,
      greens: false,
      goal: false,
      children: [
        {
          name: 'endor',
          id: '1',
          scope: 1,
          active: false,
          focus: false,
          tracked: false,
          greens: true,
          goal: false,
          limit: true,
          flow: 1,
          children: [],
          parent: 'alderaan',
          angl: 50,
          dist: 200,
          ring: 0,
        },

        {
          name: 'tatooine',
          id: '3',
          scope: 1,
          active: true,
          focus: false,
          tracked: true,
          greens: false,
          goal: false,
          flow: 3,
          children: [],
          parent: 'alderaan',
          limit: true,
          angl: 290,
          dist: 130,
          ring: 0,
        },

        {
          name: 'jakku',
          id: '2',
          scope: 1,
          active: false,
          focus: false,
          tracked: false,
          greens: false,
          goal: false,
          flow: 2,
          children: [
            {
              name: 'naboo',
              id: '2.1',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              children: [],
              parent: 'jakku',
              limit: true,
              greens: false,
              goal: true,
              flow: 1,
              angl: 120,
              dist: 110,
              ring: 0,
            },
          ],
          parent: 'alderaan',
          limit: false,
          angl: 170,
          dist: 130,
        },
      ],
    },
  ],
  max: 8,
  initialId: 3,
  initialPosition: 'tatooine',
  initialFocus: false,
  initialParent: 'alderaan',
  charge: 'endor',
  goal: 'naboo',
  thisLevel: 1,
  nextLevel: 'leveltwo',
};
