export default {
  level: [
    {
      name: 'new earth',
      id: '0',
      scope: 0,
      active: true,
      focus: false,
      tracked: true,
      limit: false,
      greens: false,
      goal: false,
      children: [
        {
          name: 'jupiter',
          id: '1',
          scope: 1,
          active: false,
          focus: true,
          tracked: false,
          greens: false,
          goal: false,
          flow: 1,
          children: [
            {
              name: 'valerie',
              id: '1.1',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              greens: false,
              children: [],
              limit: true,
              goal: false,
              flow: 1,
              angl: 10,
              dist: 140,
              ring: 0,
            },

            {
              name: 'lucy',
              id: '1.2',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              greens: false,
              goal: false,
              children: [
                {
                  name: 'max',
                  id: '1.2.1',
                  scope: 3,
                  active: false,
                  focus: false,
                  tracked: false,
                  greens: false,
                  children: [],
                  limit: true,
                  goal: false,
                  flow: 1,
                  angl: 100,
                  dist: 80,
                  ring: 0,
                },

                {
                  name: 'anna',
                  id: '1.2.2',
                  scope: 3,
                  active: false,
                  focus: false,
                  tracked: false,
                  greens: false,
                  children: [],
                  limit: true,
                  goal: false,
                  flow: 2,
                  angl: 190,
                  dist: 80,
                  ring: 2,
                },

                {
                  name: 'sam',
                  id: '1.2.3',
                  scope: 3,
                  active: false,
                  focus: false,
                  tracked: false,
                  greens: false,
                  children: [],
                  limit: true,
                  goal: false,
                  flow: 3,
                  angl: 290,
                  dist: 80,
                  ring: 0,
                },
              ],

              flow: 2,
              angl: 130,
              dist: 170,
              ring: 0,
            },

            {
              name: 'pluto',
              id: '1.3',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              greens: false,
              children: [],
              limit: true,
              goal: false,
              flow: 3,
              angl: 250,
              dist: 130,
              ring: 0,
            },
          ],
          angl: 50,
          dist: 300,
          ring: 0,
        },

        {
          name: 'gaia',
          id: '2',
          scope: 1,
          active: false,
          focus: false,
          tracked: false,
          greens: false,
          goal: false,
          flow: 2,
          children: [
            {
              name: 'venus',
              id: '2.1',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              children: [],
              limit: true,
              greens: true,
              goal: false,
              flow: 1,
              angl: 10,
              dist: 150,
              ring: 0,
            },

            {
              name: 'ash',
              id: '2.2',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              greens: false,
              children: [],
              limit: true,
              goal: false,
              flow: 2,
              angl: 130,
              dist: 150,
              ring: 0,
            },

            {
              name: 'neptun',
              id: '2.3',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              greens: false,
              children: [],
              limit: true,
              goal: false,
              flow: 3,
              angl: 250,
              dist: 140,
              ring: 2,
            },
          ],
          angl: 170,
          dist: 300,
        },

        {
          name: 'yin',
          id: '3',
          scope: 1,
          active: false,
          focus: false,
          tracked: false,
          greens: false,
          goal: false,
          flow: 3,
          children: [
            {
              name: 'goa',
              id: '3.1',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              greens: false,
              children: [],
              limit: true,
              goal: false,
              flow: 1,
              angl: 70,
              dist: 150,
              ring: 0,
            },

            {
              name: 'runa',
              id: '3.2',
              scope: 2,
              parent: 'gaia',
              order: 3,
              active: false,
              focus: false,
              tracked: false,
              greens: false,
              seeds: false,
              goal: false,
              children: [
                {
                  name: 'jose',
                  id: '3.2.1',
                  scope: 3,
                  active: false,
                  focus: false,
                  tracked: false,
                  greens: false,
                  children: [],
                  limit: true,
                  goal: false,
                  flow: 1,
                  angl: 90,
                  dist: 90,
                  ring: 0,
                },

                {
                  name: 'mars',
                  id: '3.2.2',
                  scope: 3,
                  active: false,
                  focus: false,
                  tracked: false,
                  greens: false,
                  children: [],
                  limit: true,
                  goal: false,
                  flow: 2,
                  angl: 250,
                  dist: 120,
                  ring: 0,
                },

                {
                  name: 'svea',
                  id: '3.2.3',
                  scope: 3,
                  active: false,
                  focus: false,
                  tracked: false,
                  greens: false,
                  children: [],
                  limit: true,
                  goal: true,
                  flow: 3,
                  angl: 320,
                  dist: 80,
                  ring: 2,
                },
              ],

              flow: 2,
              angl: 190,
              dist: 140,
              ring: 0,
            },

            {
              name: 'leo',
              id: '3.3',
              scope: 2,
              active: false,
              focus: false,
              tracked: false,
              greens: false,
              limit: true,
              goal: false,
              children: [],
              flow: 3,
              angl: 310,
              dist: 120,
              ring: 1,
            },
          ],
          angl: 290,
          dist: 300,
          ring: 0,
        },
      ],
    },
  ],

  max: 8,
  initialPosition: 'new earth',
  initialId: 0,
  initialFocus: 'jupiter',
  charge: 'venus',
  goal: 'svea',
  thisLevel: 3,
  nextLevel: 'levelone',
};
