export default {
  level: [
    {
      name: 'devi',
      id: '0',
      active: true,
      tracked: true,
      children: [
        {
          name: 'thor',
          id: '1',
          focus: true,
          parent: 'devi',
          children: [
            {
              name: 'odin',
              id: '1.1',
              parent: 'thor',
              children: [],
              limit: true,
              angl: 10,
              dist: 140,
              ring: 2,
            },

            {
              name: 'parvati',
              id: '1.2',
              parent: 'thor',
              children: [],
              limit: true,
              angl: 130,
              dist: 170,
              ring: 1,
            },
          ],
          angl: 50,
          dist: 200,
          ring: 0,
        },

        {
          name: 'shiva',
          id: '2',
          parent: 'devi',
          children: [
            {
              name: 'hanuman',
              id: '2.1',
              parent: 'shiva',
              children: [],
              limit: true,
              angl: 10,
              dist: 150,
              ring: 0,
            },

            {
              name: 'neptun',
              id: '2.2',
              parent: 'shiva',
              children: [],
              limit: true,
              angl: 250,
              dist: 140,
              ring: 0,
            },
          ],
          angl: 170,
          dist: 300,
        },

        {
          name: 'athena',
          id: '3',
          flow: 3,
          parent: 'devi',
          children: [
            {
              name: 'aurora',
              id: '3.1',
              parent: 'athena',
              children: [],
              limit: true,
              angl: 170,
              dist: 150,
              ring: 2,
            },

            {
              name: 'venus',
              id: '3.2',
              goal: true,
              parent: 'athena',
              children: [],
              limit: true,
              angl: 290,
              dist: 140,
              ring: 0,
            },
          ],
          angl: 290,
          dist: 130,
          ring: 0,
        },
      ],
    },
  ],
  max: 9,
  initialId: 0,
  initialPosition: 'devi',
  initialFocus: 'thor',
  initialParent: false,
  charge: 'hanuman',
  goal: 'venus',
  thisLevel: 3,
  nextLevel: 'levelfour',
  atronautName: '',
  galaxyName: 'home of gods',
};
