import Head from 'next/head'
import styled, {css} from "styled-components";
import { Field } from "../components/field";
import { Cockpit } from "../components/cockpit";

export default function App () {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MyMain>
        <Center>
        <Cockpit/>
        </Center>
        </MyMain>
      </main>

    </div>
  )
}

// GALAXY ELEMENT STYLE

const Center = styled.div`
height:500px;
width:500px;
position:relative;
display:flex;
justify-content:center;
align-items:center;
`

const MyMain = styled.div`
height:100vh;
width:100vw;
display:flex;
justify-content:center;
align-items:center;
background-image: linear-gradient(to right, #434343 0%, black 100%);
`


