import Head from 'next/head';
import { OutroPlayAgain } from '../components/intro-outro/outro-play-again';

export default function App() {
  return (
    <div>
      <Head>
        <title>lush3000</title>
        <meta name="" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <OutroPlayAgain />
      </main>
    </div>
  );
}
